apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alert
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: pod-alerts
    rules:
    - alert: PodRestartingTooMuch
      expr: kube_pod_container_status_restarts_total{namespace="demo"} > 3
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "Pod restarting frequently"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting too often."